version: "3.8"
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
  api:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --app-dir src
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
